{
 "title": "JMeter Performance Dashboard",
 "description": "Dashboard для мониторинга системных метрик и бизнес-показателей JMeter",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<h2 style=\"color:orange;\">Бизнес метрики из Jmetr</h2>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "\n<h2 style=\"color:orange;\">Системные метрики</h2>\n"
   }
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "description": "Процент запросов, завершившихся ошибкой",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT (sum(\"countError\") / sum(\"count\")) * 100 AS \"error_rate_percent\"\nFROM \"jmeter\"\nWHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Throughput ",
   "type": "stat",
   "description": "Среднее количество запросов в секунду за последние 10 секунд",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"count\") / 10 AS \"requests_per_sec\"\nFROM \"jmeter\"\nWHERE $timeFilter\nGROUP BY time(10s) fill(null)"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "Общее количество запросов, выполненных в выбранном интервале времени.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"count\") AS \"total_requests\"\nFROM \"jmeter\"\nWHERE $timeFilter"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "description": "\"Средняя загрузка CPU, вычисленная как сумма времени, занятого системными и пользовательскими процессами\".",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "query": "SELECT mean(\"usage_user\") AS \"usage_user\"\nFROM \"cpu\"\nWHERE \"cpu\" = 'cpu-total' AND $timeFilter\nGROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT mean(\"usage_system\") AS \"usage_system\"\nFROM \"cpu\"\nWHERE \"cpu\" = 'cpu-total' AND $timeFilter\nGROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "Response Time 90th Percentile (ms)",
   "type": "timeseries",
   "description": "Время отклика при 90-м перцентиле, измеренное в миллисекундах.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT mean(\"pct90.0\") AS \"response_time_90_percentile\"\nFROM \"jmeter\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Disk Usage (%)",
   "type": "timeseries",
   "description": "Процент использования дискового пространства. Показывает, какая часть общей емкости диска занята",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "SELECT mean(\"used_percent\")  AS \"disk_usage_percent\"\nFROM \"disk\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Response Time 95th Percentile (ms)",
   "type": "timeseries",
   "description": "Время отклика, которое не превышается в 95% запросов, измеряется в миллисекундах.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT mean(\"pct95.0\") AS \"response_time_95_percentile\"\nFROM \"jmeter\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Disk Response Time (ms)",
   "type": "timeseries",
   "description": "Время отклика дисковой подсистемы, измеряемое в миллисекундах. Показывает среднее время, затрачиваемое на выполнение операций ввода-вывода диска.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT mean(\"io_time\") AS \"disk_response_time_ms\"\nFROM \"diskio\"\nWHERE $timeFilter\nGROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Throughput (Запросы в секунду)",
   "type": "timeseries",
   "description": "Показывает среднее количество запросов, выполненных системой за секунду. Эта метрика отражает нагрузку на тестируемую систему.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "SELECT mean(\"count\") AS \"throughput\"\nFROM \"jmeter\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "description": "Процент использования оперативной памяти системы. Показывает, какая часть общей памяти занята активными процессами и кэшами",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "query": "SELECT mean(\"used_percent\") AS \"memory_usage_percent\"\nFROM \"mem\"\nWHERE $timeFilter\nGROUP BY time($interval) fill(null)\n"
    }
   ]
  },
  {
   "title": "Error Rate (%) (Процент ошибок)",
   "type": "timeseries",
   "description": "Процент неудачных запросов от общего количества.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "SELECT mean(\"countError\") / mean(\"count\") * 100 AS \"error_rate\"\nFROM \"jmeter\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Network Traffic (Bytes Sent/Received)",
   "type": "timeseries",
   "description": "Отображает средний объем сетевого трафика, отправленного и полученного системой за выбранный период времени. Значения измеряются в байтах в секунду.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "SELECT mean(\"bytes_sent\") AS \"Bytes Sent\", mean(\"bytes_recv\") AS \"Bytes Received\"\nFROM \"net\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}